// react-form/src/App.tsx
import { PTabsBar, PToast } from '@porsche-design-system/components-react';
import { useState } from 'react';
import { SignUpReducer } from './sign-up/sign-up-reducer';
import { SignUpRhf } from './sign-up/sign-up-rhf';
import { SignUpTanstack } from './sign-up/sign-up-tanstack';

const VARIANTS = [
  { label: 'useReducer', Form: SignUpReducer },
  { label: 'TanStack Form', Form: SignUpTanstack },
  { label: 'React Hook Form', Form: SignUpRhf },
];

export function App() {
  const [activeTabIndex, setActiveTabIndex] = useState(0);
  const ActiveForm = VARIANTS[activeTabIndex].Form;

  return (
    <div className="flex min-h-dvh w-dvw flex-col items-center justify-center gap-10 p-8">
      <PTabsBar
        activeTabIndex={activeTabIndex}
        onUpdate={(e) => setActiveTabIndex(e.detail.activeTabIndex)}
      >
        {VARIANTS.map((variant) => (
          <button key={variant.label} type="button">
            {variant.label}
          </button>
        ))}
      </PTabsBar>

      <ActiveForm />

      <PToast />
    </div>
  );
}

// vue-form/src/App.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  PorscheDesignSystemProvider,
  PTabsBar,
  PToast,
} from '@porsche-design-system/components-vue';
import SignUpReactivity from './sign-up/SignUpReactivity.vue';
import SignUpVeeValidate from './sign-up/SignUpVeeValidate.vue';
import SignUpTanstack from './sign-up/SignUpTanstack.vue';

const variants = [
  { label: 'Reactivity', component: SignUpReactivity },
  { label: 'VeeValidate', component: SignUpVeeValidate },
  { label: 'TanStack Form', component: SignUpTanstack },
];
const activeTabIndex = ref(0);
const activeComponent = computed(
  () => variants[activeTabIndex.value]?.component ?? SignUpReactivity,
);
</script>

<template>
  <PorscheDesignSystemProvider>
    <div class="flex min-h-dvh w-dvw flex-col items-center justify-center gap-10 p-8">
      <PTabsBar
        :active-tab-index="activeTabIndex"
        @update="(e: { activeTabIndex: number }) => (activeTabIndex = e.activeTabIndex)"
      >
        <button v-for="variant in variants" :key="variant.label" type="button">
          {{ variant.label }}
        </button>
      </PTabsBar>

      <component :is="activeComponent" />

      <PToast />
    </div>
  </PorscheDesignSystemProvider>
</template>
